switch:
- name: "light_1_1"
  command_topic: "bestin/room1/light1/command"
  state_topic: "bestin/room1/light1/state"
  icon: mdi:lightbulb
- name: "light_1_2"
  command_topic: "bestin/room1/light2/command"
  state_topic: "bestin/room1/light2/state"
  icon: mdi:lightbulb
- name: "light_1_3"
  command_topic: "bestin/room1/light3/command"
  state_topic: "bestin/room1/light3/state"
  icon: mdi:lightbulb
- name: "light_1_4"
  command_topic: "bestin/room1/light4/command"
  state_topic: "bestin/room1/light4/state"
  icon: mdi:lightbulb
- name: "light_2_1"
  command_topic: "bestin/room2/light1/command"
  state_topic: "bestin/room2/light1/state"
  icon: mdi:lightbulb
- name: "light_2_2"
  command_topic: "bestin/room2/light2/command"
  state_topic: "bestin/room2/light2/state"
  icon: mdi:lightbulb
- name: "light_3_1"
  command_topic: "bestin/room3/light1/command"
  state_topic: "bestin/room3/light1/state"
  icon: mdi:lightbulb
- name: "light_3_2"
  command_topic: "bestin/room3/light2/command"
  state_topic: "bestin/room3/light2/state"
  icon: mdi:lightbulb
- name: "light_4_1"
  command_topic: "bestin/room4/light1/command"
  state_topic: "bestin/room4/light1/state"
  icon: mdi:lightbulb
- name: "light_4_2"
  command_topic: "bestin/room4/light2/command"
  state_topic: "bestin/room4/light2/state"
  icon: mdi:lightbulb
- name: "light_5_1"
  command_topic: "bestin/room5/light1/command"
  state_topic: "bestin/room5/light1/state"
  icon: mdi:lightbulb
- name: "light_5_2"
  command_topic: "bestin/room5/light2/command"
  state_topic: "bestin/room5/light2/state"
  icon: mdi:lightbulb
- name: "light_all"
  command_topic: "bestin/LightAll/power/command"
  state_topic: "bestin/LightAll/power/state"
  icon: mdi:lightbulb
- name: "outlet_1_1"
  command_topic: "bestin/room1/outlet1/command"
  state_topic: "bestin/room1/outlet1/state"
  icon: mdi:power-socket-de
- name: "outlet_1_2"
  command_topic: "bestin/room1/outlet2/command"
  state_topic: "bestin/room1/outlet2/state"
  icon: mdi:power-socket-de
- name: "outlet_2_1"
  command_topic: "bestin/room2/outlet1/command"
  state_topic: "bestin/room2/outlet1/state"
  icon: mdi:power-socket-de
- name: "outlet_2_2"
  command_topic: "bestin/room2/outlet2/command"
  state_topic: "bestin/room2/outlet2/state"
  icon: mdi:power-socket-de
- name: "outlet_3_1"
  command_topic: "bestin/room3/outlet1/command"
  state_topic: "bestin/room3/outlet1/state"
  icon: mdi:power-socket-de
- name: "outlet_3_2"
  command_topic: "bestin/room3/outlet2/command"
  state_topic: "bestin/room3/outlet2/state"
  icon: mdi:power-socket-de
- name: "outlet_4_1"
  command_topic: "bestin/room4/outlet1/command"
  state_topic: "bestin/room4/outlet1/state"
  icon: mdi:power-socket-de
- name: "outlet_4_2"
  command_topic: "bestin/room4/outlet2/command"
  state_topic: "bestin/room4/outlet2/state"
  icon: mdi:power-socket-de
- name: "outlet_5_1"
  command_topic: "bestin/room5/outlet1/command"
  state_topic: "bestin/room5/outlet1/state"
  icon: mdi:power-socket-de
- name: "outlet_5_2"
  command_topic: "bestin/room5/outlet2/command"
  state_topic: "bestin/room5/outlet2/state"
  icon: mdi:power-socket-de
- name: "standby_power_1"
  command_topic: "bestin/room1/idlePower/command"
  state_topic: "bestin/room1/idlePower/state"
  icon: mdi:power-socket-de
- name: "standby_power_2"
  command_topic: "bestin/room2/idlePower/command"
  state_topic: "bestin/room2/idlePower/state"
  icon: mdi:power-socket-de
- name: "standby_power_3"
  command_topic: "bestin/room3/idlePower/command"
  state_topic: "bestin/room3/idlePower/state"
  icon: mdi:power-socket-de
- name: "standby_power_4"
  command_topic: "bestin/room4/idlePower/command"
  state_topic: "bestin/room4/idlePower/state"
  icon: mdi:power-socket-de
- name: "standby_power_5"
  command_topic: "bestin/room5/idlePower/command"
  state_topic: "bestin/room5/idlePower/state"
  icon: mdi:power-socket-de
- name: "gas"
  command_topic: "bestin/gas/power/command"
  state_topic: "bestin/gas/power/state"
  icon: mdi:gas-cylinder
- name: "doorlock"
  command_topic: "bestin/doorlock/power/command"
  state_topic: "bestin/doorlock/power/state"
  icon: mdi:door
- name: "elevator"
  command_topic: "bestin/elevator/call/command"
  state_topic: "bestin/elevator/call/state"
  icon: mdi:elevator

sensor:
- name: "power_1_1"
  state_topic: "bestin/room1/curPower1/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_1_2"
  state_topic: "bestin/room1/curPower2/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_1_3"
  state_topic: "bestin/room1/curPower3/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_2_1"
  state_topic: "bestin/room2/curPower1/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_2_2"
  state_topic: "bestin/room2/curPower2/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_3_1"
  state_topic: "bestin/room3/curPower1/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_3_2"
  state_topic: "bestin/room3/curPower2/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_4_1"
  state_topic: "bestin/room4/curPower1/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_4_2"
  state_topic: "bestin/room4/curPower2/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_5_1"
  state_topic: "bestin/room5/curPower1/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_5_2"
  state_topic: "bestin/room5/curPower2/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "evsensor"
  state_topic: "bestin/elevator/direction/state"
  icon: mdi:elevator
- name: "evsensor_direction"
  state_topic: "bestin/elevator/floor/state"
  icon: mdi:elevator
  

climate:
- name: "thermostat_1"
  mode_state_topic: "bestin/thermo1/power/state"
  mode_command_topic: "bestin/thermo1/power/command"
  temperature_state_topic: "bestin/thermo1/setTemp/state"
  temperature_command_topic: "bestin/thermo1/setTemp/command"
  current_temperature_topic: "bestin/thermo1/curTemp/state"
  modes:
  - "off"
  - "heat"
  min_temp: 5
  max_temp: 40
  precision: 0.1
- name: "thermostat_2"
  mode_state_topic: "bestin/thermo2/power/state"
  mode_command_topic: "bestin/thermo2/power/command"
  temperature_state_topic: "bestin/thermo2/setTemp/state"
  temperature_command_topic: "bestin/thermo2/setTemp/command"
  current_temperature_topic: "bestin/thermo2/curTemp/state"
  modes:
  - "off"
  - "heat"
  min_temp: 5
  max_temp: 40
  precision: 0.1
- name: "thermostat_3"
  mode_state_topic: "bestin/thermo3/power/state"
  mode_command_topic: "bestin/thermo3/power/command"
  temperature_state_topic: "bestin/thermo3/setTemp/state"
  temperature_command_topic: "bestin/thermo3/setTemp/command"
  current_temperature_topic: "bestin/thermo3/curTemp/state"
  modes:
  - "off"
  - "heat"
  min_temp: 5
  max_temp: 40
  precision: 0.1
- name: "thermostat_4"
  mode_state_topic: "bestin/thermo4/power/state"
  mode_command_topic: "bestin/thermo4/power/command"
  temperature_state_topic: "bestin/thermo4/setTemp/state"
  temperature_command_topic: "bestin/thermo4/setTemp/command"
  current_temperature_topic: "bestin/thermo4/curTemp/state"
  modes:
  - "off"
  - "heat"
  min_temp: 5
  max_temp: 40
  precision: 0.1
- name: "thermostat_5"
  mode_state_topic: "bestin/thermo5/power/state"
  mode_command_topic: "bestin/thermo5/power/command"
  temperature_state_topic: "bestin/thermo5/setTemp/state"
  temperature_command_topic: "bestin/thermo5/setTemp/command"
  current_temperature_topic: "bestin/thermo5/curTemp/state"
  modes:
  - "off"
  - "heat"
  min_temp: 5
  max_temp: 40
  precision: 0.1
  
fan:
- name: "fan"
  state_topic: "bestin/fan/power/state"
  command_topic: "bestin/fan/power/command"
  preset_mode_command_topic: "bestin/fan/preset/command"
  preset_mode_state_topic: "bestin/fan/preset/state"
  preset_modes:
    - 'low'
    - 'medium'
    - 'high'

- name: "fan_nature"
  state_topic: "bestin/fan/nature/state"
  command_topic: "bestin/fan/nature/command"


    
