switch:
- name: "light_1_1"
  command_topic: "homenet/Room1/light1/command"
  state_topic: "homenet/Room1/light1/state"
  icon: mdi:lightbulb
- name: "light_1_2"
  command_topic: "homenet/Room1/light2/command"
  state_topic: "homenet/Room1/light2/state"
  icon: mdi:lightbulb
- name: "light_1_3"
  command_topic: "homenet/Room1/light3/command"
  state_topic: "homenet/Room1/light3/state"
  icon: mdi:lightbulb
- name: "light_1_4"
  command_topic: "homenet/Room1/light4/command"
  state_topic: "homenet/Room1/light4/state"
  icon: mdi:lightbulb
- name: "light_2_1"
  command_topic: "homenet/Room2/light1/command"
  state_topic: "homenet/Room2/light1/state"
  icon: mdi:lightbulb
- name: "light_2_2"
  command_topic: "homenet/Room2/light2/command"
  state_topic: "homenet/Room2/light2/state"
  icon: mdi:lightbulb
- name: "light_3_1"
  command_topic: "homenet/Room3/light1/command"
  state_topic: "homenet/Room3/light1/state"
  icon: mdi:lightbulb
- name: "light_3_2"
  command_topic: "homenet/Room3/light2/command"
  state_topic: "homenet/Room3/light2/state"
  icon: mdi:lightbulb
- name: "light_4_1"
  command_topic: "homenet/Room4/light1/command"
  state_topic: "homenet/Room4/light1/state"
  icon: mdi:lightbulb
- name: "light_4_2"
  command_topic: "homenet/Room4/light2/command"
  state_topic: "homenet/Room4/light2/state"
  icon: mdi:lightbulb
- name: "light_5_1"
  command_topic: "homenet/Room5/light1/command"
  state_topic: "homenet/Room5/light1/state"
  icon: mdi:lightbulb
- name: "light_5_2"
  command_topic: "homenet/Room5/light2/command"
  state_topic: "homenet/Room5/light2/state"
  icon: mdi:lightbulb
- name: "outlet_1_1"
  command_topic: "homenet/Room1/outlet1/command"
  state_topic: "homenet/Room1/outlet1/state"
  icon: mdi:power-socket-de
- name: "outlet_1_2"
  command_topic: "homenet/Room1/outlet2/command"
  state_topic: "homenet/Room1/outlet2/state"
  icon: mdi:power-socket-de
- name: "outlet_2_1"
  command_topic: "homenet/Room2/outlet1/command"
  state_topic: "homenet/Room2/outlet1/state"
  icon: mdi:power-socket-de
- name: "outlet_2_2"
  command_topic: "homenet/Room2/outlet2/command"
  state_topic: "homenet/Room2/outlet2/state"
  icon: mdi:power-socket-de
- name: "outlet_3_1"
  command_topic: "homenet/Room3/outlet1/command"
  state_topic: "homenet/Room3/outlet1/state"
  icon: mdi:power-socket-de
- name: "outlet_3_2"
  command_topic: "homenet/Room3/outlet2/command"
  state_topic: "homenet/Room3/outlet2/state"
  icon: mdi:power-socket-de
- name: "outlet_4_1"
  command_topic: "homenet/Room4/outlet1/command"
  state_topic: "homenet/Room4/outlet1/state"
  icon: mdi:power-socket-de
- name: "outlet_4_2"
  command_topic: "homenet/Room4/outlet2/command"
  state_topic: "homenet/Room4/outlet2/state"
  icon: mdi:power-socket-de
- name: "outlet_5_1"
  command_topic: "homenet/Room5/outlet1/command"
  state_topic: "homenet/Room5/outlet1/state"
  icon: mdi:power-socket-de
- name: "outlet_5_2"
  command_topic: "homenet/Room5/outlet2/command"
  state_topic: "homenet/Room5/outlet2/state"
  icon: mdi:power-socket-de
- name: "standby_power_1"
  command_topic: "homenet/Room1/idlePower/command"
  state_topic: "homenet/Room1/idlePower/state"
  icon: mdi:power-socket-de
- name: "standby_power_2"
  command_topic: "homenet/Room2/idlePower/command"
  state_topic: "homenet/Room2/idlePower/state"
  icon: mdi:power-socket-de
- name: "standby_power_3"
  command_topic: "homenet/Room3/idlePower/command"
  state_topic: "homenet/Room3/idlePower/state"
  icon: mdi:power-socket-de
- name: "standby_power_4"
  command_topic: "homenet/Room4/idlePower/command"
  state_topic: "homenet/Room4/idlePower/state"
  icon: mdi:power-socket-de
- name: "standby_power_5"
  command_topic: "homenet/Room5/idlePower/command"
  state_topic: "homenet/Room5/idlePower/state"
  icon: mdi:power-socket-de
- name: "gas"
  command_topic: "homenet/Gas/power/command"
  state_topic: "homenet/Gas/power/state"
  icon: mdi:gas-cylinder
- name: "doorlock"
  command_topic: "homenet/Doorlock/power/command"
  state_topic: "homenet/Doorlock/power/state"
  icon: mdi:door
- name: "elevator"
  command_topic: "homenet/Elevator/power/command"
  state_topic: "homenet/Elevator/power/state"
  icon: mdi:elevator
  
sensor:
- name: "power_1_1"
  state_topic: "homenet/Room1/curPower1/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_1_2"
  state_topic: "homenet/Room1/curPower2/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_1_3"
  state_topic: "homenet/Room1/curPower3/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_2_1"
  state_topic: "homenet/Room2/curPower1/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_2_2"
  state_topic: "homenet/Room2/curPower2/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_3_1"
  state_topic: "homenet/Room3/curPower1/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_3_2"
  state_topic: "homenet/Room3/curPower2/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_4_1"
  state_topic: "homenet/Room4/curPower1/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_4_2"
  state_topic: "homenet/Room4/curPower2/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_5_1"
  state_topic: "homenet/Room5/curPower1/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "power_5_2"
  state_topic: "homenet/Room5/curPower2/state"
  unit_of_measurement: "Wh"
  icon: mdi:lightning-bolt
- name: "elevator"
  state_topic: "homenet/Elevator/floor/state"
  icon: mdi:elevator


climate:
- name: "thermostat_1"
  mode_state_topic: "homenet/Thermo1/power/state"
  mode_command_topic: "homenet/Thermo1/power/command"
  temperature_state_topic: "homenet/Thermo1/setTemp/state"
  temperature_command_topic: "homenet/Thermo1/setTemp/command"
  current_temperature_topic: "homenet/Thermo1/curTemp/state"
  modes:
  - "off"
  - "heat"
  min_temp: 5
  max_temp: 40
  precision: 0.1
- name: "thermostat_2"
  mode_state_topic: "homenet/Thermo2/power/state"
  mode_command_topic: "homenet/Thermo2/power/command"
  temperature_state_topic: "homenet/Thermo2/setTemp/state"
  temperature_command_topic: "homenet/Thermo2/setTemp/command"
  current_temperature_topic: "homenet/Thermo2/curTemp/state"
  modes:
  - "off"
  - "heat"
  min_temp: 5
  max_temp: 40
  precision: 0.1
- name: "thermostat_3"
  mode_state_topic: "homenet/Thermo3/power/state"
  mode_command_topic: "homenet/Thermo3/power/command"
  temperature_state_topic: "homenet/Thermo3/setTemp/state"
  temperature_command_topic: "homenet/Thermo3/setTemp/command"
  current_temperature_topic: "homenet/Thermo3/curTemp/state"
  modes:
  - "off"
  - "heat"
  min_temp: 5
  max_temp: 40
  precision: 0.1
- name: "thermostat_4"
  mode_state_topic: "homenet/Thermo4/power/state"
  mode_command_topic: "homenet/Thermo4/power/command"
  temperature_state_topic: "homenet/Thermo4/setTemp/state"
  temperature_command_topic: "homenet/Thermo4/setTemp/command"
  current_temperature_topic: "homenet/Thermo4/curTemp/state"
  modes:
  - "off"
  - "heat"
  min_temp: 5
  max_temp: 40
  precision: 0.1
- name: "thermostat_5"
  mode_state_topic: "homenet/Thermo5/power/state"
  mode_command_topic: "homenet/Thermo5/power/command"
  temperature_state_topic: "homenet/Thermo5/setTemp/state"
  temperature_command_topic: "homenet/Thermo5/setTemp/command"
  current_temperature_topic: "homenet/Thermo5/curTemp/state"
  modes:
  - "off"
  - "heat"
  min_temp: 5
  max_temp: 40
  precision: 0.1
  
fan:
- name: "fan"
  state_topic: "homenet/Fan/power/state"
  command_topic: "homenet/Fan/power/command"
  preset_mode_command_topic: "homenet/Fan/preset/command"
  preset_mode_command_template: >
    {% if value == 'low' %}
      low
    {% elif value == 'mid' %}
      medium
    {% elif value == 'high' %}
      high
    {% elif value == 'nature ON' %}
      nature ON
    {% elif value == 'nature OFF' %}
      nature OFF
    {% else %}
      off 
    {% endif %}
  preset_mode_state_topic: "homenet/Fan/preset/state"
  preset_mode_value_template: >
    {% if value_json.FanSpeed == low %}
      low
    {% elif value_json.FanSpeed == mid %}
      medium
    {% elif value_json.FanSpeed == high %}
      high
    {% elif value_json.FanSpeed == 'nature ON' %}
      nature ON
    {% elif value_json.FanSpeed == 'nature OFF' %}
      nature OFF
    {% else %}
      off
    {% endif %}
  preset_modes:
    - 'low'
    - 'mid'
    - 'high'
    - 'nature ON'
    - 'nature OFF'


    
