switch:
- name: "light_1_1"
  command_topic: "homenet/Light1/power1/command"
  state_topic: "homenet/Light1/power1/state"
  icon: mdi:lightbulb
- name: "light_1_2"
  command_topic: "homenet/Light1/power2/command"
  state_topic: "homenet/Light1/power2/state"
  icon: mdi:lightbulb
- name: "light_1_3"
  command_topic: "homenet/Light1/power3/command"
  state_topic: "homenet/Light1/power3/state"
  icon: mdi:lightbulb
- name: "light_2_1"
  command_topic: "homenet/Light2/power1/command"
  state_topic: "homenet/Light2/power1/state"
  icon: mdi:lightbulb
- name: "light_2_2"
  command_topic: "homenet/Light2/power2/command"
  state_topic: "homenet/Light2/power2/state"
  icon: mdi:lightbulb
- name: "light_3_1"
  command_topic: "homenet/Light3/power1/command"
  state_topic: "homenet/Light3/power1/state"
  icon: mdi:lightbulb
- name: "light_3_2"
  command_topic: "homenet/Light3/power2/command"
  state_topic: "homenet/Light3/power2/state"
  icon: mdi:lightbulb
- name: "light_4_1"
  command_topic: "homenet/Light4/power1/command"
  state_topic: "homenet/Light4/power1/state"
  icon: mdi:lightbulb
- name: "light_4_2"
  command_topic: "homenet/Light4/power2/command"
  state_topic: "homenet/Light4/power2/state"
  icon: mdi:lightbulb
- name: "light_5_1"
  command_topic: "homenet/Light5/power1/command"
  state_topic: "homenet/Light5/power1/state"
  icon: mdi:lightbulb
- name: "light_5_2"
  command_topic: "homenet/Light5/power2/command"
  state_topic: "homenet/Light5/power2/state"
  icon: mdi:lightbulb

- name: "outlet_1_1"
  command_topic: "homenet/Outlet1/power1/command"
  state_topic: "homenet/Outlet1/power1/state"
  icon: mdi:power-socket-de
- name: "outlet_1_2"
  command_topic: "homenet/Outlet1/power2/command"
  state_topic: "homenet/Outlet1/power2/state"
  icon: mdi:power-socket-de
- name: "outlet_2_1"
  command_topic: "homenet/Outlet2/power1/command"
  state_topic: "homenet/Outlet2/power1/state"
  icon: mdi:power-socket-de
- name: "outlet_2_2"
  command_topic: "homenet/Outlet2/power2/command"
  state_topic: "homenet/Outlet2/power2/state"
  icon: mdi:power-socket-de
- name: "outlet_3_1"
  command_topic: "homenet/Outlet3/power1/command"
  state_topic: "homenet/Outlet3/power1/state"
  icon: mdi:power-socket-de
- name: "outlet_3_2"
  command_topic: "homenet/Outlet3/power2/command"
  state_topic: "homenet/Outlet3/power2/state"
  icon: mdi:power-socket-de
- name: "outlet_4_1"
  command_topic: "homenet/Outlet4/power1/command"
  state_topic: "homenet/Outlet4/power1/state"
  icon: mdi:power-socket-de
- name: "outlet_4_2"
  command_topic: "homenet/Outlet4/power2/command"
  state_topic: "homenet/Outlet4/power2/state"
  icon: mdi:power-socket-de
- name: "outlet_5_1"
  command_topic: "homenet/Outlet5/power1/command"
  state_topic: "homenet/Outlet5/power1/state"
  icon: mdi:power-socket-de
- name: "outlet_5_2"
  command_topic: "homenet/Outlet5/power2/command"
  state_topic: "homenet/Outlet5/power2/state"
  icon: mdi:power-socket-de

- name: "gas"
  command_topic: "homenet/Gas/power/command"
  state_topic: "homenet/Gas/power/state"
  payload_on: "OFF"
  payload_off: "OFF"
  icon: mdi:gas-cylinder
- name: "elevator"
  command_topic: "homenet/Elevator/call/command"
  state_topic: "homenet/Elevator/call/state"
  payload_on: "ON"
  payload_off: "ON"
  icon: mdi:elevator
  
sensor:
- name: "evsensor"
  state_topic: "homenet/Elevator/floor/state"
  icon: mdi:elevator

climate:
- name: "thermostat_1"
  mode_state_topic: "homenet/Thermo1/power/state"
  mode_command_topic: "homenet/Thermo1/power/command"
  temperature_state_topic: "homenet/Thermo1/setTemp/state"
  temperature_command_topic: "homenet/Thermo1/setTemp/command"
  current_temperature_topic: "homenet/Thermo1/curTemp/state"
  modes:
  - "off"
  - "heat"
  min_temp: 5
  max_temp: 40
  precision: 0.1
  icon: mdi:thermostat
- name: "thermostat_2"
  mode_state_topic: "homenet/Thermo2/power/state"
  mode_command_topic: "homenet/Thermo2/power/command"
  temperature_state_topic: "homenet/Thermo2/setTemp/state"
  temperature_command_topic: "homenet/Thermo2/setTemp/command"
  current_temperature_topic: "homenet/Thermo2/curTemp/state"
  modes:
  - "off"
  - "heat"
  min_temp: 5
  max_temp: 40
  precision: 0.1
  icon: mdi:thermostat
- name: "thermostat_3"
  mode_state_topic: "homenet/Thermo3/power/state"
  mode_command_topic: "homenet/Thermo3/power/command"
  temperature_state_topic: "homenet/Thermo3/setTemp/state"
  temperature_command_topic: "homenet/Thermo3/setTemp/command"
  current_temperature_topic: "homenet/Thermo3/curTemp/state"
  modes:
  - "off"
  - "heat"
  min_temp: 5
  max_temp: 40
  precision: 0.1
  icon: mdi:thermostat
- name: "thermostat_4"
  mode_state_topic: "homenet/Thermo4/power/state"
  mode_command_topic: "homenet/Thermo4/power/command"
  temperature_state_topic: "homenet/Thermo4/setTemp/state"
  temperature_command_topic: "homenet/Thermo4/setTemp/command"
  current_temperature_topic: "homenet/Thermo4/curTemp/state"
  modes:
  - "off"
  - "heat"
  min_temp: 5
  max_temp: 40
  precision: 0.1
  icon: mdi:thermostat
- name: "thermostat_5"
  mode_state_topic: "homenet/Thermo5/power/state"
  mode_command_topic: "homenet/Thermo5/power/command"
  temperature_state_topic: "homenet/Thermo5/setTemp/state"
  temperature_command_topic: "homenet/Thermo5/setTemp/command"
  current_temperature_topic: "homenet/Thermo5/curTemp/state"
  modes:
  - "off"
  - "heat"
  min_temp: 5
  max_temp: 40
  precision: 0.1
  icon: mdi:thermostat

fan:
- name: "fan"
  state_topic: "homenet/Fan/power/state"
  command_topic: "homenet/Fan/power/command"
  preset_mode_command_topic: "homenet/Fan/preset/command"
  preset_mode_command_template: >
    {% if value == 'low' %}
      low
    {% elif value == 'medium' %}
      medium
    {% elif value == 'high' %}
      high
    {% elif value == 'nature ON' %}
      nature ON
    {% elif value == 'nature OFF' %}
      nature OFF
    {% else %}
      off 
    {% endif %}
  preset_mode_state_topic: "homenet/Fan/preset/state"
  preset_mode_value_template: >
    {% if value_json.FanSpeed == low %}
      low
    {% elif value_json.FanSpeed == medium %}
      medium
    {% elif value_json.FanSpeed == high %}
      high
    {% elif value_json.FanSpeed == 'nature ON' %}
      nature ON
    {% elif value_json.FanSpeed == 'nature OFF' %}
      nature OFF
    {% else %}
      off
    {% endif %}
  preset_modes:
    - 'low'
    - 'medium'
    - 'high'
    - 'nature ON'
    - 'nature OFF'
  icon: mdi:fan


    