name: EasyRoll Smart Blind
version: 1.0.0
slug: easyroll
description: Add-on for EasyRoll Smart Blind
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - share:rw
url: https://github.com/harwin1/ha-addons/blob/main/easyroll_blind
startup: application
boot: auto
uart: true
options:
  blinds: []
  mqtts: 
    - server: 192.168.1.1
      port: 1883
      username: null
      password: null
  scan_interval: 300  
  command_interval: 30
schema:
  blinds: 
    - str  
  mqtts: 
    - server: str
      port: int
      username: str?
      password: str?
  scan_interval: int
  command_interval: int
